name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore SAM.sln

      - name: Build solution
        run: dotnet build SAM.sln --configuration Release --no-restore

      - name: Create release package
        run: |
          $tagName = "${{ github.ref_name }}"
          $folderName = "SAM-HC-$tagName"
          New-Item -ItemType Directory -Path $folderName
          Get-ChildItem -Path Release\* -Exclude Debug | Copy-Item -Destination $folderName -Recurse
          Compress-Archive -Path $folderName -DestinationPath "$folderName.zip"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: SAM-HC-${{ github.ref_name }}.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
