name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore SAM.sln

      - name: Build solution
        run: dotnet build SAM.sln --configuration Release --no-restore

      - name: Install Inno Setup
        run: choco install innosetup -y

      - name: Update version in Inno Setup script
        run: |
          $version = "${{ github.ref_name }}".TrimStart('v')
          (Get-Content SAM-HC-Setup.iss) -replace '#define MyAppVersion ".*"', "#define MyAppVersion `"$version`"" | Set-Content SAM-HC-Setup.iss

      - name: Build installer
        run: iscc SAM-HC-Setup.iss

      - name: Create portable zip package
        run: |
          $tagName = "${{ github.ref_name }}"
          $folderName = "SAM-HC-Portable-$tagName"
          New-Item -ItemType Directory -Path $folderName
          Get-ChildItem -Path Release\* -Exclude Debug | Copy-Item -Destination $folderName -Recurse
          Compress-Archive -Path $folderName -DestinationPath "$folderName.zip"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            SAM-HC-Installer-${{ github.ref_name }}.exe
            SAM-HC-Portable-${{ github.ref_name }}.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
